name: Flutter Android CI

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Java
      uses: actions/setup-java@v4
      with:
        distribution: 'zulu'
        java-version: '17'

    - name: Set up Flutter (Latest Stable)
      uses: subosito/flutter-action@v2
      with:
        channel: 'stable'

    - name: Install Dependencies
      run: flutter pub get

    # Play Store ke liye final signed AAB bundle banana
    - name: Build App Bundle (AAB)
      run: flutter build appbundle --release
      env:
        PLAY_STORE_KEY_ALIAS: ${{ secrets.PLAY_STORE_KEY_ALIAS }}
        PLAY_STORE_KEY_PASSWORD: ${{ secrets.PLAY_STORE_KEY_PASSWORD }}
        PLAY_STORE_KEYSTORE_PASSWORD: ${{ secrets.PLAY_STORE_KEYSTORE_PASSWORD }}

    # Final AAB file ko GitHub Artifacts par upload karna
    - name: Upload App Bundle to GitHub Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: QR-Shield-PlayStore-AAB
        path: build/app/outputs/bundle/release/app-release.aab
