name: Flutter Android CI

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Java
      uses: actions/setup-java@v4
      with:
        distribution: 'zulu'
        java-version: '17'

    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.22.2' # آپ کا موجودہ فلٹر ورژن

    - name: Install Dependencies
      run: flutter pub get

    # پہلے آپ کی ٹیسٹنگ کے لیے اصلی APK بنانا
    - name: Build APK for Local Testing
      run: flutter build apk --release

    # پلے اسٹور کے لیے فائنل AAB بنانا
    - name: Build App Bundle (AAB)
      run: flutter build appbundle --release
      env:
        PLAY_STORE_KEY_ALIAS: ${{ secrets.PLAY_STORE_KEY_ALIAS }}
        PLAY_STORE_KEY_PASSWORD: ${{ secrets.PLAY_STORE_KEY_PASSWORD }}
        PLAY_STORE_KEYSTORE_PASSWORD: ${{ secrets.PLAY_STORE_KEYSTORE_PASSWORD }}

    # جادوئی سٹیپ: ٹیسٹنگ APK کو گٹ ہب پر ڈاؤن لوڈ کے لیے رکھنا
    - name: Upload Testing APK to GitHub Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: QR-Shield-Testing-APK
        path: build/app/outputs/flutter-apk/app-release.apk
